FROM alwaysai/edgeiq:eyecloud-armv7hf-latest

# Defines our working directory in container
WORKDIR /usr/src/app

# Copies the package.json first for better cache on later pushes
COPY . /usr/src/app/

RUN pip install -r requirements.txt

CMD ["python", "app.py"]

