FROM alwaysai/edgeiq:eyecloud-armv7hf-latest

RUN apt update && apt install usbutils vim

# Defines our working directory in container
WORKDIR /usr/src/app

COPY . .

RUN pip install -r requirements.txt

CMD ["python", "app.py"]
